inherit_from: .rubocop_todo.yml

require: rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  # Do not attempt to police vendored code
  Exclude:
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true
