inherit_from: .rubocop_todo.yml

require: rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  # Do not attempt to police vendored code
  Exclude:
    - 'vendor/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Style/FrozenStringLiteralComment:
  Enabled: false

# https://rubystyle.guide/#max-line-length specifies 80 char.
# Explicitly setting the rubocop default to document the decision not
# to change it for now.
Layout/LineLength:
  Max: 120

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true
